var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { 
                        // title: '42首页',
                        // date: '2017年3月3日 教学周：第12周',
                        // note: '每日鸡汤：广阔的天空，乌云不会停留太久，它来自天空，也消失于空',
                        // news_src1:'#',
                        // news_srctext1:'学院公告',
                        // news_src2:'#',
                        // news_srctext2:'校园新鲜事',
                        // news_src3:'#',
                        // news_srctext3:'科技FUN',
                        // news_src4:'#',
                        // news_srctext4:'更多',
                        // news_img1:'./images/img1.jpg',
                        // news_img2:'./images/img2.jpg',
                        // news_img3:'./images/img3.jpg',
                        // news_imgtext1:'英语系2015级"阅读造就你...',
                        // news_imgtext2:'英语系2015级"阅读造就你...',
                        // news_imgtext3:'英语系2015级"阅读造就你...',
                        // news_detail1:'#',
                        // news_detailtext1:'关于举办<校友会>09期 "阅读造就你我 第一..."',
                        // news_detail1:'#',
                        // news_detailtext2:'关于举办<校友会>09期 "阅读造就你我 第一..."',
                        // news_detail2:'#',
                        // news_detailtext3:'关于举办<校友会>09期 "阅读造就你我 第一..."',
                        // news_detail3:'#',
                        // news_detailtext4:'关于举办<校友会>09期 "阅读造就你我 第一..."',
                        // news_detail4:'#',
                        // news_detailtext5:'关于举办<校友会>09期 "阅读造就你我 第一..."',
                        // news_detail5:'#',
                        // news_detailtext6:'关于举办<校友会>09期 "阅读造就你我 第一..."',
                        // news_detail6:'#',
                        // news_detailtext7:'关于举办<校友会>09期 "阅读造就你我 第一..."',
                        // news_detail7:'#',
                        // news_detailtext8:'关于举办<校友会>09期 "阅读造就你我 第一..."',
                        // news_detail8:'#',
                        // news_detailtext9:'关于举办<校友会>09期 "阅读造就你我 第一..."',
                        // news_detail9:'#',
                        // news_detailtext10:'关于举办<校友会>09期 "阅读造就你我 第一..."',
                        // news_detail10:'#',
                        // movies_src1:'#',
                        // movies_srctext1:'近日更新',
                        // movies_src2:'#',
                        // movies_srctext2:'热门推荐',
                        // movies_src3:'#',
                        // movies_srctext3:'电影',
                        // movies_src4:'#',
                        // movies_srctext4:'动漫',
                        // movies_src5:'#',
                        // movies_srctext5:'更多',
                        // movies_img1:'./images/img1.jpg',
                        // movies_img2:'./images/img2.jpg',
                        // movies_img3:'./images/img3.jpg',
                        // movies_imgtext1:'釜山行',
                        // movies_imgtext2:'釜山行',
                        // movies_imgtext3:'釜山行',
                        // movies_img4:'./images/img1.jpg',
                        // movies_img5:'./images/img2.jpg',
                        // movies_img6:'./images/img3.jpg',
                        // movies_imgtext4:'釜山行',
                        // movies_imgtext5:'釜山行',
                        // movies_imgtext6:'釜山行',
                        // softs_src1:'#',
                        // softs_srctext1:'下载站',
                        // softs_src2:'#',
                        // softs_srctext2:'设计类软件',
                        // softs_src3:'#',
                        // softs_srctext3:'开发类软件',
                        // softs_src4:'#',
                        // softs_srctext4:'更多',
                        // soft_title1:'PSCC2017',
                        // soft_size1:'1804Mb',
                        // soft_src1:'#',
                        // soft_title2:'PSCC2017',
                        // soft_size2:'1804Mb',
                        // soft_src2:'#',
                        // soft_title3:'PSCC2017',
                        // soft_size3:'1804Mb',
                        // soft_src3:'#',
                        // soft_title4:'PSCC2017',
                        // soft_size4:'1804Mb',
                        // soft_src4:'#',
                        // soft_title5:'PSCC2017',
                        // soft_size5:'1804Mb',
                        // soft_src5:'#',
                        // soft_title6:'PSCC2017',
                        // soft_size6:'1804Mb',
                        // soft_src6:'#',
                        // soft_title7:'PSCC2017',
                        // soft_size7:'1804Mb',
                        // soft_src7:'#',
                        // soft_title8:'PSCC2017',
                        // soft_size8:'1804Mb',
                        // soft_src8:'#',
                        // nav_src1:'#',
                        // nav_text1:'16课件网',
                        // nav_src2:'#',
                        // nav_text2:'学生邮箱',
                        // nav_src3:'#',
                        // nav_text3:'教师邮箱',
                        // nav_src4:'#',
                        // nav_text4:'新教务网',
                        // nav_src5:'#',
                        // nav_text5:'综合门户',
                        // nav_src6:'#',
                        // nav_text6:'素质教育',
                        // nav_src7:'#',
                        // nav_text7:'UFS系统',
                        // nav_src8:'#',
                        // nav_text8:'Campus',
                        // notice_src1:'#',
                        // notice_text1:'2017年3月3日',
                        // notice_src2:'#',
                        // notice_text2:'2017年3月3日',
                        // notice_src3:'#',
                        // notice_text3:'2017年12月31日',
                        // ad_src:'#',
                        // ad_img:'./images/ad.jpg',
                        // intro_text:'北冥逐日是一个由42技术小组创立，为东软全校师生提供全方面服务的网站。它于2003年10月19号正式上线，致力于打造东软非官方专业门户。',
                        // extension_src1:'#',
                        // extension_text1:'合作推广',
                        // extension_src2:'#',
                        // extension_text2:'招贤纳士',
                        // extension_src3:'#',
                        // extension_text3:'成长日记',
                        // contact_src:'#',
                        // contact_text:'42team@nou.com.cn'


    });
});

module.exports = router;

module.exports = router;
